# Generated by Django 5.2.4 on 2025-07-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create_post', 'can add post'), ('can_edit_post', 'can edit post'), ('can_delete_post', 'can delete psot'), ('can_view_post', 'can view post')]},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined']},
        ),
    ]
