# Generated by Django 5.2.4 on 2025-07-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='date joined', verbose_name='date joined'),
        ),
    ]
