# Generated by Django 5.2.4 on 2025-07-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0005_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Username', max_length=200, null=True),
        ),
    ]
