# Generated by Django 5.2.4 on 2025-07-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0010_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
