# Generated by Django 5.2.4 on 2025-07-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0016_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='profile picture'),
        ),
    ]
