# Generated by Django 5.2.4 on 2025-07-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
